blank_issues_enabled: true
contact_links:
  - name: 💬 Question or general discussion
    url: https://github.com/Lohomi15/doubleii/discussions
    about: Not a bug or a feature request? Ask or share here.
